services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # The official image uses KAFKA_NODE_ID, not KAFKA_CFG_NODE_ID
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:9093'
      
      # Listener Configs
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_DEFAULT_PARTITION_COUNT: 3
      
      # KRaft cluster ID automatically generates if not provided, 
      # but you can explicitly map it if needed.
  # spark:
  #   image: apache/spark:3.5.6 
  #   container_name: spark_app
  #   user: root  # Gives Spark permission to read/write to your mounted local folder
  #   # Force the container to stay alive regardless of default image behavior
  #   command: tail -f /dev/null  
  #   volumes:
  #     - .:/opt/spark/apps # Mounts your local project folder into a safe container path
  #   working_dir: /opt/spark/apps
  #   depends_on:
  #     - kafka
  #   environment:
  #     - PYTHONPATH=/opt/spark/apps
# services:
#   kafka:
#     image: apache/kafka:latest
#     container_name: kafka
#     ports:
#       - "9092:9092"

#     environment:
#       KAFKA_NODE_ID: 1
#       KAFKA_PROCESS_ROLES: 'broker,controller'
#       KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'

#       KAFKA_LISTENERS: 'INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093'

#       KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka:29092,EXTERNAL://localhost:9092'

#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT'

#       KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
#       KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
#   schema-registry:
#     image: confluentinc/cp-schema-registry:7.6.0
#     container_name: schema-registry
#     depends_on:
#       - kafka
#     ports:
#       - "8081:8081"
#     environment:
#       SCHEMA_REGISTRY_HOST_NAME: schema-registry
#       SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
#       SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092